<?php
namespace App\Utils;

use EasySwoole\Core\Component\Logger;
use Symfony\Component\HttpFoundation\Request as SymfonyRequest;

class Request extends SymfonyRequest
{
    public function __construct(array $query = array(), array $request = array(), array $attributes = array(), array $cookies = array(), array $files = array(), array $server = array(), $content = null){
        parent::__construct($query,$request,$attributes ,$cookies,$files,$server,$content);
    }
    /**
     * @param bool $asResource
     * @return string
     */
    public function getContent($asResource = false)
    {
        $this->content = Context::get()->rawContent();

        return $this->content;
    }

    public static function createFromGlobals()
    {
        return parent::createFromGlobals(); // TODO: Change the autogenerated stub
    }


    public static function clearRequestFactory(){
        self::$requestFactory = null;
    }

}



//
//use Symfony\Component\HttpFoundation\Request as utilsRequest;
//
//class Request extends utilsRequest
//{
//    public function __construct(array $query = array(), array $request = array(), array $attributes = array(), array $cookies = array(), array $files = array(), array $server = array(), $content = null)
//    {
//        parent::__construct($query, $request, $attributes, $cookies, $files, $server, $content);
//    }
//
//    public function getContent($asResource = false)
//    {
//        //return parent::getContent($asResource); // TODO: Change the autogenerated stub
//        $this->content = Context::get()->getSwooleRequest()->rawContent();
//
//        return $this->content;
//
//    }
//}